import { useMemo, useState } from 'react';
import { Image, Pressable, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { MagnifyingGlass, UserCircle } from 'phosphor-react-native';

import { NotificationBell } from '@/components/home/notification-bell';
import { ProfileSilhouette } from '@/components/profile-silhouette';
import { Alert, Caption, EmptyState, Loading, PageSubtitle, PageTitle, Screen } from '@/components/ui';
import { api, apiMessage } from '@/lib/api';
import { useAuth } from '@/store/auth';
import { rgb, space, useTheme, radius } from '@/theme';
import { Txt } from '@/theme/fonts';

interface Conversation { withUserId: string; displayName: string; photoUrl: string | null; profileId?: string | null; gender?: string | null; lastMessage: string | null; lastMessageAt: string | null; lastMessageMine: boolean; unread: number; online: boolean; kind?: 'match' | 'inquiry' | null; }
type Tab = 'All' | 'Matches';

export default function ChatList() {
  const theme = useTheme(); const router = useRouter(); const user = useAuth((s) => s.user); const [term, setTerm] = useState(''); const [tab, setTab] = useState<Tab>('All');
  const query = useQuery({ queryKey: ['conversations'], queryFn: async () => (await api.get('/chat/conversations')).data as Conversation[], retry: false, refetchInterval: 20_000 });
  const rows = useMemo(() => (query.data ?? []).filter((row) => `${row.displayName} ${row.lastMessage ?? ''}`.toLowerCase().includes(term.trim().toLowerCase()) && (tab === 'All' || tab === 'Matches' && row.kind === 'match')), [query.data, term, tab]);
  return <Screen><Header initial={user?.email?.[0]} /><View><PageTitle>Chat</PageTitle><PageSubtitle>Stay connected, plan together.</PageSubtitle></View><View style={{ flexDirection: 'row', alignItems: 'center', borderRadius: radius.md, backgroundColor: rgb(theme.surface), paddingLeft: space(3) }}><MagnifyingGlass size={19} color={rgb(theme.brand)} /><TextInput value={term} onChangeText={setTerm} placeholder="Search conversations..." placeholderTextColor={rgb(theme.ink[400])} style={{ flex: 1, padding: space(3), color: rgb(theme.ink[900]) }} /></View><View style={{ flexDirection: 'row', gap: space(1) }}>{(['All', 'Matches'] as Tab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={{ flex: 1, minHeight: 37, borderRadius: radius.md, justifyContent: 'center', alignItems: 'center', backgroundColor: tab === item ? rgb(theme.brand) : rgb(theme.brandSoft) }}><Caption tone={tab === item ? 'onBrand' : 'brand'}>{item}</Caption></Pressable>)}</View>{query.isPending ? <Loading rows={5} /> : query.error ? <Alert tone="critical">{apiMessage(query.error, 'Conversations could not be loaded.')}</Alert> : rows.length ? <View>{rows.map((row) => <Pressable key={row.withUserId} onPress={() => router.push({ pathname: '/chat/[id]', params: { id: row.withUserId, name: row.displayName, photo: row.photoUrl ?? '', online: String(row.online) } })} style={{ paddingVertical: space(2.5), borderBottomWidth: 1, borderBottomColor: rgb(theme.border) }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: space(2) }}>{row.photoUrl ? <Image source={{ uri: row.photoUrl }} style={{ width: 52, height: 52, borderRadius: radius.md }} /> : row.profileId ? <ProfileSilhouette gender={row.gender} style={{ width: 52, height: 52, borderRadius: radius.md }} /> : <UserCircle size={52} color={rgb(theme.ink[400])} />}<View style={{ flex: 1, gap: 2 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: space(1) }}><Caption numberOfLines={1} style={{ flex: 1, fontSize: 15, fontWeight: '700', color: rgb(theme.ink[800]) }}>{row.displayName}</Caption><Badge label={row.kind === 'match' ? 'Match' : 'Inquiry'} /></View><Caption numberOfLines={1} tone={row.unread ? 'default' : 'faint'}>{row.lastMessage ? `${row.lastMessageMine ? 'You: ' : ''}${row.lastMessage}` : 'No messages yet'}</Caption></View><View style={{ alignItems: 'flex-end', gap: space(1) }}><Caption tone="faint">{when(row.lastMessageAt)}</Caption>{row.unread ? <View style={{ minWidth: 20, height: 20, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: rgb(theme.brand) }}><Caption tone="onBrand" style={{ fontSize: 11 }}>{row.unread}</Caption></View> : null}</View></View></Pressable>)}</View> : <EmptyState title="No conversations yet">Accepted matches appear here when you are ready to talk.</EmptyState>}</Screen>;
}
function Header({ initial }: { initial?: string }) { const theme = useTheme(); return <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><View style={{ width: 40 }} /><Txt serif style={{ fontSize: 30, fontWeight: '600', color: rgb(theme.brand) }}>WOW</Txt><View style={{ flexDirection: 'row', gap: space(1) }}><NotificationBell /><View style={{ width: 40, height: 40, borderRadius: radius.md, backgroundColor: rgb(theme.brandSoft), alignItems: 'center', justifyContent: 'center' }}><Txt style={{ fontWeight: '700', color: rgb(theme.brandStrong) }}>{initial?.toUpperCase() ?? 'U'}</Txt></View></View></View>; }
function Badge({ label }: { label: string }) { const theme = useTheme(); return <View style={{ borderRadius: radius.md, paddingHorizontal: space(1.5), paddingVertical: 2, backgroundColor: rgb(theme.brandSoft) }}><Caption tone="brand" style={{ fontSize: 10 }}>{label}</Caption></View>; }
function when(value: string | null): string { if (!value) return ''; const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toDateString() === new Date().toDateString() ? date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : date.toLocaleDateString([], { day: 'numeric', month: 'short' }); }
