import { BadRequestException } from '@nestjs/common';
import { existsSync, promises as fs } from 'fs';
import { join, normalize, resolve, sep } from 'path';
import { contentTypeFor } from './content-types';
import { StorageSettings } from './storage-config';
import { ObjectInfo, PutOptions, StorageDriver, UrlOptions } from './storage.driver';

/** A host that names this machine to itself and to nothing else. */
const LOOPBACK = /^(localhost|127(?:\.\d{1,3}){3}|\[::1\])$/i;

/**
 * The file a key names under the local store's root, or a refusal.
 *
 * The key is generated by the platform, but it arrives back from the client,
 * so it is re-checked here rather than trusted. `..` in it would otherwise
 * write anywhere the process can reach.
 */
export function resolveLocalPath(rootDir: string, key: string): string {
  const root = resolve(rootDir);
  const target = resolve(join(root, normalize(key)));
  if (!target.startsWith(root + sep) && target !== root) {
    throw new BadRequestException('Bad object key');
  }
  return target;
}

/**
 * The API's own disk, served by MockStorageController.
 *
 * What every local and test stack runs on, with nothing to configure. Objects
 * are public — anyone with the URL can fetch it — which is why this is not the
 * production store; the URL is permanent, so it is stored exactly as it is
 * handed out, as it always has been.
 */
export class LocalStorageDriver implements StorageDriver {
  readonly name = 'mock' as const;
  readonly private = false;

  constructor(private readonly s: StorageSettings) {}

  async presignPut(key: string, options: PutOptions) {
    // The same address for both, which is the property that matters: the file
    // you PUT is the file you GET.
    return { url: this.base(options.requestOrigin) + `/${key}`, headers: {} };
  }

  async urlFor(key: string, options: UrlOptions = {}) {
    return `${this.base(options.requestOrigin)}/${key}`;
  }

  keyFromUrl(url: string): string | null {
    try {
      const path = new URL(url).pathname;
      const at = path.indexOf('/mock-storage/');
      return at >= 0 ? decodeURIComponent(path.slice(at + '/mock-storage/'.length)) : null;
    } catch {
      return null;
    }
  }

  async head(key: string): Promise<ObjectInfo | null> {
    const path = resolveLocalPath(this.s.mockStorageDir, key);
    if (!existsSync(path)) return null;
    const stat = await fs.stat(path);
    return stat.isFile() ? { size: stat.size, contentType: contentTypeFor(key) } : null;
  }

  async delete(key: string): Promise<void> {
    await fs.rm(resolveLocalPath(this.s.mockStorageDir, key), { force: true });
  }

  async readStart(key: string, maxBytes: number): Promise<Buffer | null> {
    const path = resolveLocalPath(this.s.mockStorageDir, key);
    if (!existsSync(path)) return null;
    const file = await fs.open(path, 'r');
    try {
      const buf = Buffer.alloc(maxBytes);
      const { bytesRead } = await file.read(buf, 0, maxBytes, 0);
      return buf.subarray(0, bytesRead);
    } finally {
      await file.close();
    }
  }

  /**
   * Where the local store is reached, for the device that asked.
   *
   * The configured base comes from APP_BASE_URL, which on a local stack is
   * `http://localhost:8085`: this machine, to this machine and nothing else. A
   * phone on the same Wi-Fi was handed an upload URL on its own loopback, so
   * every photograph failed at the PUT, and a browser on a second laptop failed
   * the same way. When the configured base is loopback, the origin the request
   * actually reached is used instead. A real address in configuration always
   * wins, and so does a CDN.
   */
  private base(requestOrigin?: string): string {
    if (this.s.cdnBaseUrl) return this.s.cdnBaseUrl;
    const configured = this.s.mockBaseUrl;
    if (!requestOrigin) return configured;
    try {
      const url = new URL(configured);
      if (!LOOPBACK.test(url.hostname)) return configured;
      const origin = new URL(requestOrigin);
      return `${origin.protocol}//${origin.host}${url.pathname.replace(/\/+$/, '')}`;
    } catch {
      return configured;
    }
  }
}
